version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: programwithgio-app
    restart: 'no'
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: programwithgio-nginx
    restart: 'no'
    ports:
      - 80:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d